### ISSUE TITLE
suboptimales build script

### ISSUE THREAD

**Issue by viisauksena** [FreifunkLippe/site-ffl#17]
alles super,
nur immer alles neu bauen muss nicht sein
https://github.com/FreifunkLippe/site-ffl/blob/master/build_fflip_fw.sh#L19
https://github.com/FreifunkLippe/site-ffl/blob/master/build_fflip_fw.sh#L20
https://github.com/FreifunkLippe/site-ffl/blob/master/build_fflip_fw.sh#L21

siehe hier https://forum.freifunk.net/t/fehler-beim-bauen/11773/34?u=fuzzle

**Comment by collimas** [comment]
Script wurde optimiert und erweitert.

**Comment by viisauksena** [comment]
ich seh keine veränerung in dem buildscript , vergessen zu pushen?

**Comment by collimas** [comment]
Wurde noch nicht in den Master gepusht. Schau bitte in den Branch v2016.1.x-Experimental.

**Comment by viisauksena** [comment]
sieht ganz gut aus,
konsequenter weise könnte man aber auch auch noch einen 
git pull 
für dieses repo mit einbauen , damit da auch wirklich der letzte kram eingebaut wird, aber da öäuft das skript ja auch schon.. naja, nicht so wichtig

**Comment by collimas** [comment]
An welcher Stelle meinst du?

viisauksena <notifications@github.com> schrieb:
>sieht ganz gut aus,
>konsequenter weise könnte man aber auch auch noch einen 
>git pull 
>für dieses repo mit einbauen , damit da auch wirklich der letzte kram
>eingebaut wird, aber da öäuft das skript ja auch schon.. naja, nicht so
>wichtig
>
>---
>You are receiving this because you modified the open/close state.
>Reply to this email directly or view it on GitHub:
>https://github.com/FreifunkLippe/site-ffl/issues/17#issuecomment-212506595

Mit freundlichen Grüßen
Best Regards

Michael Brinkmann

http://freifunk-bad-salzuflen.de
http://freifunk-lippe.de
http://map.freifunk-lippe.de

Threema-ID: 2TW6WHXH
OpenPGP ID: 1AC8BF8D

**Comment by viisauksena** [comment]
Da wo das submodule auch geupdated wird. Kann ja sein das euer update skript sich verandert. Dann muss das danach aber stoppen und neu starten . Muss man sich was cleveres zu ausdenken wenn man das einbaut.
Evtl kannst du dir noch gedanken zu dem openwrt kmod pubkey machen. Das ein anderes thema .. und wichtig wenn ihr solche kernelmodule auch bereit stellt zum nachinstallieren.
--
Jens Freiburg
Bitte benutze PGP Verschlüsselung, danke

Am 20. April 2016 18:51:07 MESZ, schrieb Michael Brinkmann <notifications@github.com>:
>An welcher Stelle meinst du?
>
