### ISSUE TITLE
Kopieren von site-configs für die einzelnen Domänen

### ISSUE THREAD

**Issue by Tronde** [FreifunkLippe/site-ffl#27]
Hey @collimas,

ich glaube, ich habe noch einen Fehler im build_fflip_fw.sh-Skript gefunden.
~~~
# If gluon directory exists update to latest master and push this into actual repo
if [ -d "$DIR/gluon" ]
  then
    cd $DIR/gluon
      if [ ! -d "$DIR/gluon/site" ]; then
        mkdir -p $DIR/gluon/site
      fi
    cp $DIR/sites-d1/ff/site.* $DIR/gluon/site/
    make update
    git pull
    git submodule update --remote gluon
  else
    # If gluon directory does not exist do a fresh clone frome the Freifunk-Gluon Repo
    cd $DIR
    git clone https://github.com/freifunk-gluon/gluon.git gluon -b $RELEASE
    mkdir -p $DIR/gluon/site
    cp $DIR/sites-d1/ff/site.* $DIR/gluon/site/
    cd $DIR/gluon
    make update
    git pull
    git submodule update --remote gluon
fi
~~~

Es werden hier nur die site.*-Dateien aus dem Verzeichnis ''$DIR/sites-d1/ff/'' kopiert. Was ist mit den weiteren Domänen? Nutzt du diese gar nicht? Oder änderst du das Skript dafür jedes mal händisch?

Ich kann das Skript so anpassen, dass alle site.*-Dateien aus allen ''sites-d?''-Verzeichnissen kopiert werden. Bitte gib mir eine Rückmeldung, ob ich das einbauen soll und ob dies auch die "experimental"-Verzeichnisse umfassen soll.

LG\\
Tronde

**Comment by collimas** [comment]
Wie schon geschrieben: an dieser Stelle ist es unerheblich, welche
site.conf und site.mk Dateien benutzt werden. Es geht nur darum, dass
eine valide Konfiguration vorhanden ist, um das "make update"
durchführen zu können.

Während der eigentlichen Kompilierung werden dann die "richtigen"
Konfigurationen verwendet.

Du musst also nichts modifizieren, das funktioniert so problemlos.

Mit freundlichen Grüßen
Best regards

Michael Brinkmann

Threema ID: 2TW6WHXH

Am 07.09.2016 um 22:21 schrieb Joerg Kastning:
