### ISSUE TITLE
mksites.sh Fehler bei der Erzeugung von "Freifunk" SSID site.conf

### ISSUE THREAD

**Issue by collimas** [FreifunkLippe/site-ffl#3]
Bei der SSID "Freifunk" wird durch das Script "Freifunk.freifunk.net" erzeugt, was ein wenig seltsam aussieht. Die SSID soll einfach "Freifunk" lauten.

Ansonsten funktioniert das Scipt wie gewünscht.

**Comment by Tronde** [comment]
Die SSID "Freifunk" stellt einen Sonderfall dar, da sie nicht dem Muster der übrigen Site-Configs entspricht.

Wo bzw. an welcher Stelle wird diese Konfiguration im Livebetrieb verwendet, so dass dies wahrgenommen werden könnte?

Wenn du möchtest, kann ich diesen Sonderfall aber auch durch ein paar zusätzliche Zeilen im Script korrigieren.

**Comment by collimas** [comment]
Bisher gibt es diese SSID nicht im Livebetrieb. Da aber bereits
diskutiert wurde, deutschlandweit einheitlich diese SSID zu verwenden,
möchte ich diese gerne als Vorbereitung schon mitbauen können, wenn du
das Script also erweitern könntest, wäre das wunderbar.

**Comment by Tronde** [comment]
Habe eine Sonderbehandlung für die SSID Freifunk eingebaut und getestet.

**Comment by collimas** [comment]
Super. Dann pull doch in den Master!

Mit freundlichen Grüßen
Best regards

Michael Brinkmann

http://freifunk-bad-salzuflen.de
http://freifunk-lippe.de
http://map.freifunk-lippe.de

Threema ID: 2TW6WHXH
OpenPGP ID: 1AC8BF8D

Am 14.11.2015 um 17:27 schrieb Joerg Kastning:
